name: Claude AI Assistant

# 监听所有相关的 GitHub 事件
on:
  # PR 事件：创建、更新、编辑、标签、分配、关闭、重新打开
  pull_request:
    types: [opened, synchronize, edited, labeled, assigned, closed, reopened, ready_for_review]

  # PR 审查事件
  pull_request_review:
    types: [submitted, edited]

  # PR 审查评论
  pull_request_review_comment:
    types: [created, edited]

  # Issue 事件：创建、编辑、标签、分配、关闭、重新打开
  issues:
    types: [opened, edited, labeled, assigned, closed, reopened]

  # Issue 和 PR 评论
  issue_comment:
    types: [created, edited]

jobs:
  claude-assistant:
    # 智能触发条件：状态变动自动触发 OR @ 提及触发
    # 禁止所有 bot 触发，防止无限循环
    if: |
      !endsWith(github.actor, '[bot]') && (
        github.event_name == 'pull_request' ||
        github.event_name == 'pull_request_review' ||
        github.event_name == 'issues' ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
      )

    runs-on: ubuntu-latest
    timeout-minutes: 30

    # 完整权限配置
    permissions:
      contents: write          # 代码读写、分支创建、提交
      pull-requests: write     # PR 全功能操作
      issues: write            # Issue 全功能操作
      actions: read            # 读取 CI 状态
      id-token: write          # OIDC 认证

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # 完整历史，便于分析

      - name: Run Claude Code Assistant
        uses: anthropics/claude-code-action@v1
        env:
          # 支持自定义 Base URL（代理服务）
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
        with:
          # API 认证
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # 触发配置
          trigger_phrase: "@claude"

          # 智能提示：根据事件类型自动调整行为
          prompt: |
            REPO: ${{ github.repository }}
            EVENT: ${{ github.event_name }}
            ${{ github.event.pull_request.number && format('PR NUMBER: {0}', github.event.pull_request.number) || '' }}
            ${{ github.event.issue.number && format('ISSUE NUMBER: {0}', github.event.issue.number) || '' }}
            ACTOR: ${{ github.actor }}

            你是一个全能的 GitHub 助手。根据当前事件类型，执行相应的操作：

            ## 铁律（违反即失败）：
            1. **永远不要直接提交代码到 main 分支** - main 是生产分支，任何直接提交都是严重违规
            2. **永远不要创建指向 main 的 PR** - 所有 PR 必须指向 dev 分支
            3. **永远不要绕过 dev 分支** - 代码必须先进入 dev，经过测试后才能合并到 main
            4. **所有代码变更必须遵循标准工作流**：创建新分支 → 提交 → 推送 → PR 到 dev

            ## 标准 Git 工作流：
            ```bash
            # 1. 创建并切换到新分支
            git checkout -b fix/issue-<number>-<description>  # Bug 修复（来自 Issue）
            git checkout -b feat/pr-<number>-<description>    # 新功能（来自 PR）

            # 2. 提交代码（确保先运行 git config 检查身份）
            git add .
            # ⚠️ 如果是修复 Issue，commit message 必须包含关闭关键字
            git commit -m "fix: 描述修复内容, close #<issue-number>"  # Issue 场景
            git commit -m "feat: 描述新功能"                            # PR 场景

            # 3. 推送到远程
            git push origin <branch-name>

            # 4. 创建 PR 到 dev 分支（必须指定 --base dev）
            # Issue 场景：PR body 中也要包含关闭关键字
            gh pr create --base dev --title "Fix: ..." --body "Close #<issue-number>\n\n详细描述"
            # PR 场景：正常描述即可
            gh pr create --base dev --title "..." --body "详细描述"
            ```

            **GitHub 自动关闭 Issue 的关键字**：
            - `close #123` / `closes #123` / `fix #123` / `fixes #123` / `resolve #123` / `resolves #123`
            - 可用于 commit message 或 PR 描述中，推荐两处都写
            - PR 合并到 dev 后，相关 Issue 会自动关闭

            ## 对于 PR 事件（opened, synchronize, edited）：
            1. **代码审查**：
               - 分析代码质量、潜在 bug、安全问题、性能问题
               - 使用 `mcp__github_inline_comment__create_inline_comment` 添加行内评论
               - 使用 `gh pr comment` 添加总体评论

            2. **自动标签**：
               - 分析 PR 内容，使用 `gh pr edit --add-label` 添加适当标签
               - 标签类型：bug, enhancement, documentation, breaking-change, needs-review
               - 优先级：priority-high, priority-medium, priority-low

            3. **代码修复**（如果需要且用户明确请求）：
               - **严格遵循标准 Git 工作流**（见上方）
               - 创建新分支：`git checkout -b fix/pr-<number>-<description>`
               - 修改代码并提交：`git add . && git commit -m "fix: ..."`
               - 推送分支：`git push origin <branch-name>`
               - 创建 PR 到 dev：`gh pr create --base dev --title "..." --body "..."`
               - **禁止**：直接提交到当前分支、直接推送到 main、创建指向 main 的 PR

            ## 对于 Issue 事件（opened, edited）：
            1. **自动分类和标签**：
               - 首先运行 `gh label list` 获取可用标签
               - 分析 Issue 类型：bug, feature-request, question, documentation
               - 评估优先级：P1 (critical), P2 (high), P3 (medium), P4 (low)
               - 使用 `gh issue edit --add-label` 添加标签

            2. **重复检测**：
               - 使用 `gh search issues` 查找类似 Issue
               - 如果发现重复，添加 duplicate 标签并评论说明

            3. **自动回复**：
               - 对于问题类 Issue，提供详细解答
               - 对于 bug 报告，确认问题并提供临时解决方案
               - 对于功能请求，评估可行性并提供建议

            4. **代码修复**（如果用户明确请求）：
               - **严格遵循标准 Git 工作流**
               - 创建分支：`git checkout -b fix/issue-<number>-<description>`
               - **关键**：commit message 必须包含 `close #<issue-number>`
               - PR body 也要包含关闭关键字
               - 示例：`gh pr create --base dev --title "Fix #123: ..." --body "Close #123\n\n修复了..."`

            ## 对于评论事件（@ 提及）：
            1. **智能响应**：
               - 回答用户问题
               - 提供代码示例
               - 解释技术细节
               - 如果需要修复代码，**严格遵循标准 Git 工作流**：
                 * 创建新分支（不要直接修改当前分支）
                 * **如果是 Issue 评论**：commit message 必须包含 `close #<issue-number>`
                 * **如果是 PR 评论**：正常的 commit message 即可
                 * 提交代码后推送到远程
                 * 创建 PR 到 dev 分支（必须使用 `--base dev`）
                 * Issue 场景示例：`gh pr create --base dev --title "Fix #123: ..." --body "Close #123\n\n..."`
                 * 永远不要直接提交到 main 或创建指向 main 的 PR

            2. **上下文理解**：
               - 阅读完整的对话历史
               - 理解 PR/Issue 的完整上下文
               - 提供针对性的建议

            ## 工具使用指南：
            - 标签管理：`gh issue edit <number> --add-label "label1,label2"`
            - PR 标签：`gh pr edit <number> --add-label "label1,label2"`
            - 评论：`gh issue comment <number> --body "content"` 或 `gh pr comment <number> --body "content"`
            - 搜索：`gh search issues "keywords" --limit 5`
            - 查看详情：`gh issue view <number>` 或 `gh pr view <number>`

            ## 重要原则：
            - **分支管理铁律**：所有代码变更必须通过新分支 → PR 到 dev，禁止直接操作 main
            - 始终保持专业和友好的语气
            - 提供可操作的建议
            - 如果不确定，说明不确定的原因
            - 自动化操作（标签、分类）不需要评论说明，静默执行
            - 只在需要与用户交互时才发表评论
            - **所有 PR 必须指向 dev 分支**，使用 `gh pr create --base dev`

          # Claude 配置参数
          claude_args: |
            --max-turns 999
            --allowedTools "Read,Write,Edit,Bash(gh:*),Bash(git:*),Bash(npm:*),Bash(pnpm:*),Bash(yarn:*),mcp__github_inline_comment__create_inline_comment"

          # 其他配置
          use_commit_signing: true
          # 禁用进度追踪
          track_progress: false
